import type { Metadata } from "next";
import { Inter, Noto_Sans, Work_Sans } from "next/font/google";
import "./globals.css";
import BackToTopButton from "@/components/layout/BackToTop";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { cn } from "@/lib/utils";

const notoSansHeading = Noto_Sans({
   subsets: ["latin"],
   variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const work_Sans = Work_Sans({
   subsets: ["latin"],
});

export const metadata: Metadata = {
   description: "Generated by create next app",
   title: "MDX Blog",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={cn("font-sans", inter.variable, notoSansHeading.variable)}
         data-scroll-behavior="smooth"
      >
         <body
            className={`${work_Sans.className} antialiased max-w-7xl mx-auto`}
            suppressHydrationWarning
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
               <BackToTopButton />
            </ThemeProvider>
         </body>
      </html>
   );
}
